version: '3.8'

services:
  finance-bot:
    build: .
    container_name: finance-controller-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Sao_Paulo
    networks:
      - finance-bot-network

networks:
  finance-bot-network:
    driver: bridge 