services:
  - type: web
    name: finance-controller-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TZ
        value: America/Sao_Paulo
      - key: MPLBACKEND
        value: Agg 